on:
  push:
    tags:
      - 'v*' # e.g. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Checkout code
      uses: actions/checkout@master
    
    - run: yarn install

    - name: Set version in Version.purs
      run: sed -i "s/develop/${{ github.ref }}/g" src/Version.purs
    
    - run: cat src/Version.purs
    
    - name: Build bundle
      run: yarn bundle

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: false
        prerelease: false
